server:
  port: 9999

spring:
  kafka:
    bootstrap-servers: localhost:9092
  main:
    #    允许bean的名字重复,后者覆盖前者
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: info

resourceone:
  portal:
    #r1_home目录
    resourceone-home: D:\work\r1home\ResourceOneHome_LXZJZ
    #resourceone数据源
    resourceone-datasource:
      url: jdbc:oracle:thin:@10.100.220.110:1521:ywxt
      username: CNGC_FRAMEWORK_SHENGCHAN
      password: CNGC_FRAMEWORK_SHENGCHAN
      driver-class-name: oracle.jdbc.driver.OracleDriver